{{- if .Values.llamaParseLayoutDetectionApi.enabled }}
{{- if .Values.llamaParseLayoutDetectionApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llamaParseLayoutDetectionApi.serviceAccountName" . }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with .Values.llamaParseLayoutDetectionApi.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with .Values.llamaParseLayoutDetectionApi.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.llamaParseLayoutDetectionApi.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}
{{- end }}
