apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with.Values.frontend.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with.Values.frontend.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.autoscaling.minReplicas }}
  {{- else }}
  replicas: {{ .Values.frontend.replicas }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "llamacloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.frontend.name }}
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.frontend.name }}
        {{- include "llamacloud.labels" . | nindent 8 }}
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.frontend.name | default "frontend" }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
          {{- if not .Values.global.config.existingLicenseKeySecret }}
          - name: LLAMACLOUD_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "llamacloud.fullname" . }}-license-key
                key: llamacloud-license-key
          {{- end }}
          - name: HOSTNAME
            value: 0.0.0.0
          - name: NEXT_PUBLIC_BACKEND_URL
            value: {{ printf "http://%s-%s:%d" (include "llamacloud.fullname" .) .Values.backend.name (.Values.backend.service.port | int) | quote }}
          {{- range $key, $value := .Values.frontend.extraEnvVariables }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          {{- if (or .Values.frontend.envFromSecretName .Values.frontend.envFromConfigMapName) }}
          envFrom:
          {{- if .Values.frontend.envFromConfigMapName }}
          - configMapRef:
              name: {{ .Values.frontend.envFromConfigMapName }}
          {{- end }}
          {{- if .Values.frontend.envFromSecretName }}
          - secretRef:
              name: {{ .Values.frontend.envFromSecretName }}
          {{- end }}
          {{- end }}
          {{- with .Values.frontend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.frontend.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
