apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with .Values.frontend.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with .Values.frontend.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.global.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ .Values.global.progressDeadlineSeconds | int }}
  {{- end }}
  {{- if .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.autoscaling.minReplicas }}
  {{- else }}
  replicas: {{ .Values.frontend.replicas }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "llamacloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.frontend.name }}
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.frontend.name }}
        {{- include "llamacloud.labels" . | nindent 8 }}
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.frontend.name | default "frontend" }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
          - name: LLAMACLOUD_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                {{- if .Values.global.config.existingLicenseKeySecret }}
                name: {{ .Values.global.config.existingLicenseKeySecret }}
                {{- else }}
                name: {{ include "llamacloud.fullname" . }}-license-key
                {{- end }}
                key: llamacloud-license-key
          - name: HOSTNAME
            value: 0.0.0.0
          - name: BACKEND_URL
            {{- if .Values.ingress.enabled }}
            value: {{ printf "%s://%s" .Values.ingress.scheme .Values.ingress.host | quote }}
            {{- else }}
            value: {{ printf "http://%s-%s:%d" (include "llamacloud.fullname" .) .Values.backend.name (.Values.backend.service.port | int) | quote }}
            {{- end }}
          {{- if .Values.backend.config.qdrant.enabled }}
          - name: NEXT_PUBLIC_BYOC_HAS_MANAGED_QDRANT
            value: "true"
          {{- end }}
          {{- if .Values.frontend.config.tls.enabled }}
          - name: NODE_EXTRA_CA_CERTS
            value: "{{ .Values.frontend.config.tls.caCertMountPath }}/{{ .Values.frontend.config.tls.caCertKey }}"
          {{- end }}
          {{- with .Values.frontend.extraEnvVariables }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.frontend.config.tls.enabled }}
          - name: ca-certs
            mountPath: {{ .Values.frontend.config.tls.caCertMountPath }}
            readOnly: true
          {{- end }}
          {{- with .Values.frontend.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.frontend.config.tls.enabled }}
        - name: ca-certs
          {{- if .Values.frontend.config.tls.caCertSecretName }}
          secret:
            secretName: {{ .Values.frontend.config.tls.caCertSecretName }}
          {{- else }}
          configMap:
            name: {{ .Values.frontend.config.tls.caCertConfigMapName }}
          {{- end }}
        {{- end }}
        {{- with .Values.frontend.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
