{{- if not .Values.llamaParse.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.llamaParse.name }}-secret
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
data:
  {{- if and (eq .Values.global.cloudProvider "aws") (not .Values.global.existingAwsSecretName) }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.config.awsAccessKeyId | default "" | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.config.awsSecretAccessKey | default "" | b64enc | quote }}
  {{- end }}
  {{- if and .Values.llamaParse.config.openAiApiKey (not .Values.llamaParse.config.existingOpenAiApiKeySecret) }}
  OPENAI_API_KEY: {{ .Values.llamaParse.config.openAiApiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.llamaParse.config.anthropicAPIKey (not .Values.llamaParse.config.existingAnthropicAPIKeySecret) }}
  ANTHROPIC_API_KEY: {{ .Values.llamaParse.config.anthropicAPIKey | default "" | b64enc | quote }}
  {{- end }}
{{- end }}
