{{- if .Values.parsebench.enabled }}
{{- $backendComponent := include "llamacloud.component.backend" $ | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: parsebench-config
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  PARSEBENCH_JOB_IMAGE: {{ .Values.parsebench.image | default (printf "%s:%s" "docker.io/llamaindex/llamacloud-parsebench" .Chart.AppVersion) | quote }}
  PARSEBENCH_JOB_IMAGE_PULL_POLICY: {{ .Values.parsebench.imagePullPolicy | quote }}
  PARSEBENCH_DEFAULT_API_BASE_URL: {{ printf "http://%s:80" $backendComponent.name | quote }}
  PARSEBENCH_OUTPUT_BUCKET: {{ ((.Values.config).storageBuckets).parseOutput | quote }}
  {{- if and (not .Values.parsebench.apiKeySecretName) .Values.parsebench.apiKey }}
  PARSEBENCH_JOB_API_KEY_SECRET_NAME: {{ printf "%s-parsebench" .Release.Name | quote }}
  {{- else if .Values.parsebench.apiKeySecretName }}
  PARSEBENCH_JOB_API_KEY_SECRET_NAME: {{ .Values.parsebench.apiKeySecretName | quote }}
  {{- end }}
{{- end }}
