apiVersion: v2
name: llamacloud
description: A Helm chart to deploy LlamaCloud and all of its necessary services.

home: https://github.com/run-llama/helm-charts

sources:
- https://github.com/run-llama/helm-charts

maintainers:
- name: Jerry Liu
  email: jerry@runllama.ai
  url: https://github.com/jerryjliu
- name: Simon Suo
  email: simon@runllama.ai
  url: https://github.com/Disiok
- name: Jonathan Whitaker
  email: jonathan@runllama.ai
  url: https://github.com/jonathan-whitaker

keywords:
- llamaindex
- llamacloud
- rag

version: 0.7.6
appVersion: "0.7.6"

dependencies:
  - name: temporal
    version: ~0.73.0
    repository: https://go.temporal.io/helm-charts
    condition: temporal.deploy
    alias: temporal-subchart
  - name: llama-agents
    version: ~0.12.0
    repository: oci://registry-1.docker.io/llamaindex
    condition: llamaAgents.deploy
    alias: llama-agents-subchart
