apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  IS_DEPLOYED: "true"
  DEPLOYMENT_MODE: "prod"
  PARSE_PREMIUM: "true"
  ALLOWED_INDEX: "true"
{{- if not (.Values.mongodb).enabled }}
  MONGO_DISABLED: "true"
{{- end }}
{{- if not (.Values.rabbitmq).enabled }}
  AMQP_DISABLED: "true"
{{- end }}
{{- if not ((.Values.config).v1).enabled }}
  V1_ENABLED: "false"
{{- end }}