{{- if .Values.llamaParseOcr.enabled }}
{{- if .Values.llamaParseOcr.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.llamaParseOcr.name }}
spec:
  {{- if .Values.llamaParseOcr.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.llamaParseOcr.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.llamaParseOcr.name }}
{{- end }}
{{- end }}
