{{- if .Values.llamaParseOcr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.llamaParseOcr.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with.Values.llamaParseOcr.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with.Values.llamaParseOcr.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.llamaParseOcr.service.type }}
  ports:
    - port: {{ .Values.llamaParseOcr.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llamacloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.llamaParseOcr.name }}
{{- end }}
