{{- if .Values.llamaParseOcr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llamaParseOcr.serviceAccountName" . }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with.Values.llamaParseOcr.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with.Values.llamaParseOcr.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.llamaParseOcr.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}
