{{- if not .Values.jobsService.envFromConfigMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsService.name }}-config
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
data:
  IS_DEPLOYED: "true"
  DEPLOYMENT_MODE: "prod"
  LOG_LEVEL: {{ .Values.jobsService.config.logLevel | default "info" }}
  JOB_API_SERVICE_PORT: {{ .Values.jobsService.service.port | default 8002 | quote }}
  TRACKING_SERVICE_URL: {{ printf "http://%s-%s:%d" (include "llamacloud.fullname" .) .Values.usage.name (.Values.usage.service.port | int) | quote }}
  ALLOWED_INDEX: "true"
  PARSE_PREMIUM: "true"
  S3_DOCUMENT_BUCKET_NAME: {{ .Values.global.config.parsedDocumentsCloudBucketName | default "llama-platform-parsed-documents" }}
  S3_ETL_BUCKET_NAME: {{ .Values.global.config.parsedEtlCloudBucketName | default "llama-platform-etl" }}
  S3_EXTERNAL_COMPONENTS_BUCKET_NAME: {{ .Values.global.config.parsedExternalComponentsCloudBucketName | default "llama-platform-external-components" }}
  S3_FILE_PARSING_BUCKET_NAME: {{ .Values.global.config.parsedFileParsingCloudBucketName | default "llama-platform-file-parsing" }}
  S3_RAW_FILE_BUCKET_NAME: {{ .Values.global.config.parsedRawFileCloudBucketName | default "llama-platform-raw-files" }}
  S3_LLAMA_CLOUD_PARSE_OUTPUT_BUCKET_NAME: {{ .Values.global.config.parsedLlamaCloudParseOutputCloudBucketName | default "llama-cloud-parse-output" }}
  S3_FILE_SCREENSHOT_BUCKET_NAME: {{ .Values.global.config.parsedFileScreenshotCloudBucketName | default "llama-platform-file-screenshots" }}
  S3_LLAMA_EXTRACT_OUTPUT_BUCKET_NAME: {{ .Values.global.config.llamaExtractOutputCloudBucketName | default "llama-platform-extract-output" }}
  LLAMA_EXTRACT_MULTIMODAL_MODEL: {{ .Values.backend.config.llamaExtractMultimodalModel | quote }}
  {{- if .Values.s3proxy.enabled }}
  S3_ENDPOINT_URL: {{ printf "http://%s-%s:%d" (include "llamacloud.fullname" .) .Values.s3proxy.name (.Values.s3proxy.service.port | int) | quote }}
  {{- end }}
{{- end }}
