apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsService.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with.Values.jobsService.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with.Values.jobsService.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.jobsService.autoscaling.enabled }}
  replicas: {{ .Values.jobsService.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llamacloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsService.name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.jobsService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsService.name }}
        {{- include "llamacloud.labels" . | nindent 8 }}
        {{- with .Values.jobsService.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jobsService.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jobsService.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.jobsService.name | default "jobs-service" }}
          securityContext:
            {{- toYaml .Values.jobsService.securityContext | nindent 12 }}
          image: "{{ .Values.jobsService.image.repository }}:{{ .Values.jobsService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jobsService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.jobsService.containerPort }}
              protocol: TCP
          command: ["poetry", "run", "start_job_service"]
          livenessProbe:
            {{- toYaml .Values.jobsService.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.jobsService.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.jobsService.resources | nindent 12 }}
          env:
          - name: LLAMACLOUD_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                {{- if .Values.global.config.existingLicenseKeySecret }}
                name: {{ .Values.global.config.existingLicenseKeySecret }}
                {{- else }}
                name: {{ include "llamacloud.fullname" . }}-license-key
                {{- end }}
                key: llamacloud-license-key
          {{- if .Values.postgresql.enabled }}
          - name: DATABASE_HOST
            value: {{ printf "%s-%s" .Release.Name "postgresql" | quote}}
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_NAME
            value: {{ .Values.postgresql.auth.database | quote }}
          - name: DATABASE_USER
            value: {{ .Values.postgresql.auth.username | quote }}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-%s" .Release.Name "postgresql" }}
                key: postgres-password
          {{- end }}
          {{- if .Values.mongodb.enabled }}
          - name: MONGODB_HOST
            value: {{ printf "%s-%s" .Release.Name (default "mongodb" .Values.mongodb.nameOverride) | quote }}
          - name: MONGODB_PORT
            value: {{ .Values.mongodb.service.port | default "27017" | quote }}
          - name: MONGODB_USER
            value: {{ .Values.mongodb.auth.rootUser | quote }}
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-%s" .Release.Name (default "mongodb" .Values.mongodb.nameOverride) | quote }}
                key: mongodb-root-password
          {{- end }}
          {{- if .Values.rabbitmq.enabled }}
          - name: JOB_QUEUE_ENDPOINT
            value: {{ printf "amqp://%s-%s:5672" (include "llamacloud.fullname" .) (default "rabbitmq" .Values.rabbitmq.nameOverride) | quote }}
          - name: JOB_QUEUE_USERNAME
            value: {{ .Values.rabbitmq.auth.username | default "user" | quote }}
          - name: JOB_QUEUE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-%s" (include "llamacloud.fullname" .) (default "rabbitmq" .Values.rabbitmq.nameOverride) | quote }}
                key: rabbitmq-password
          {{- end }}
          {{- with .Values.jobsService.extraEnvVariables }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsService.name }}-config
          {{- if .Values.global.config.existingAwsSecretName }}
          - secretRef:
              name: {{ .Values.global.config.existingAwsSecretName }}
          {{- end }}
          {{- if .Values.backend.config.existingOpenAiApiKeySecretName }}
          - secretRef:
              name: {{ .Values.backend.config.existingOpenAiApiKeySecretName }}
          {{- end }}
          {{- if and .Values.backend.config.azureOpenAi.enabled .Values.backend.config.azureOpenAi.existingSecret }}
          - secretRef:
              name: {{ .Values.backend.config.azureOpenAi.existingSecret }}
          {{- end }}
          {{- if not .Values.jobsService.externalSecrets.enabled }}
          - secretRef:
              name: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsService.name }}-secret
          {{- else }}
          {{- range .Values.jobsService.externalSecrets.secrets }}
          - secretRef:
              name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.jobsService.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.jobsService.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobsService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobsService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobsService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
