{{- if not .Values.jobsService.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsService.name }}-secret
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
data:
  {{- if and (eq .Values.global.cloudProvider "aws") .Values.global.config.awsAccessKeyId .Values.global.config.awsSecretAccessKey (not .Values.global.existingAwsSecretName) }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.config.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.config.awsSecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.backend.config.openAiApiKey (not .Values.backend.existingOpenAiApiKeySecretName) }}
  LC_OPENAI_API_KEY: {{ .Values.backend.config.openAiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3proxy.enabled }}
  S3_ENDPOINT_URL: {{ printf "http://%s-%s:%d" (include "llamacloud.fullname" .) .Values.s3proxy.name (.Values.s3proxy.service.port | int) | b64enc | quote }}
  {{- end }}
{{- end }}
