{{- if and (include "temporal.enabled" .) .Values.temporalJobsService.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporalJobsService.api.serviceAccountName" . }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with .Values.temporalJobsService.api.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with .Values.temporalJobsService.api.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.temporalJobsService.api.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}
