apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamaparse-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: llamacloud-llamaparse-ocr
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: llamacloud-llamaparse-ocr
    spec:
      serviceAccountName: llamacloud-llamaparse-ocr
      containers:
        - name: llamaparse-ocr
          image: "docker.io/llamaindex/llamacloud-llamaparse-ocr:0.1.47"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          command: ["serve"]
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health_check
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health_check
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 4
              memory: 16Gi
            requests:
              cpu: 2
              memory: 12Gi
          env:
          - name: LLAMACLOUD_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: license-key
                key: license-key
