apiVersion: v1
kind: Service
metadata:
  name: llamaparse-ocr
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: llamacloud-llamaparse-ocr
