{{- if and .Values.s3proxy.enabled (or (not .Values.s3proxy.envFromConfigMapName) (not .Values.s3proxy.envFromSecretName)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.s3proxy.name }}-config
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
data:
  {{- with .Values.s3proxy.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
