{{- if .Values.s3proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.s3proxy.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with.Values.s3proxy.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with.Values.s3proxy.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.s3proxy.autoscaling.enabled }}
  replicas: {{ .Values.s3proxy.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llamacloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.s3proxy.name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.s3proxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.s3proxy.name }}
        {{- include "llamacloud.labels" . | nindent 8 }}
        {{- with .Values.s3proxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "s3proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.s3proxy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.s3proxy.name }}
          securityContext:
            {{- toYaml .Values.s3proxy.securityContext | nindent 12 }}
          image: "{{ .Values.s3proxy.image.repository }}:{{ .Values.s3proxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.s3proxy.image.pullPolicy }}
          ports:
            - name: {{ .Values.s3proxy.name }}-http
              containerPort: {{ .Values.s3proxy.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.s3proxy.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.s3proxy.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.s3proxy.resources | nindent 12 }}
          {{- if .Values.s3proxy.extraEnvVariables }}
          env:
          {{- with .Values.s3proxy.extraEnvVariables }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          {{- if (or .Values.s3proxy.envFromSecretName .Values.s3proxy.envFromConfigMapName) }}
          envFrom:
          {{- if .Values.s3proxy.envFromConfigMapName }}
          - configMapRef:
              name: {{ .Values.s3proxy.envFromConfigMapName }}
          {{- end }}
          {{- if .Values.s3proxy.envFromSecretName }}
          - secretRef:
              name: {{ .Values.s3proxy.envFromSecretName }}
          {{- end }}
          {{- else }}
          envFrom:
          - configMapRef:
              name: {{ include "llamacloud.fullname" . }}-{{ .Values.s3proxy.name }}-config
          {{- end }}
          volumeMounts:
          - name: empty-dir
            mountPath: /tmp
            subPath: tmp-dir
      volumes:
      - name: empty-dir
        emptyDir: {}
      {{- with .Values.s3proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.s3proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.s3proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}