{{- if include "temporal.enabled" . -}}
{{- if not .Values.temporalParse.llamaParse.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.temporalParse.llamaParse.name }}-secret
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
data:
  {{- if and (eq .Values.global.cloudProvider "aws") .Values.global.config.awsAccessKeyId .Values.global.config.awsSecretAccessKey (not .Values.global.existingAwsSecretName) }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.config.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.config.awsSecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.temporalParse.llamaParse.config.openAiApiKey (not .Values.temporalParse.llamaParse.config.existingOpenAiApiKeySecret) }}
  OPENAI_API_KEY: {{ .Values.temporalParse.llamaParse.config.openAiApiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.temporalParse.llamaParse.config.azureOpenAi.enabled (not .Values.temporalParse.llamaParse.config.azureOpenAi.existingSecret ) }}
  AZURE_OPENAI_KEY: {{ .Values.temporalParse.llamaParse.config.azureOpenAi.key | b64enc | quote }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.temporalParse.llamaParse.config.azureOpenAi.endpoint | b64enc | quote }}
  AZURE_OPENAI_DEPLOYMENT_NAME: {{ .Values.temporalParse.llamaParse.config.azureOpenAi.deploymentName | b64enc | quote }}
  AZURE_OPENAI_API_VERSION: {{ .Values.temporalParse.llamaParse.config.azureOpenAi.apiVersion | b64enc | quote }}
  {{- end }}
  {{- if and .Values.temporalParse.llamaParse.config.anthropicApiKey (not .Values.temporalParse.llamaParse.config.existingAnthropicApiKeySecret) }}
  ANTHROPIC_API_KEY: {{ .Values.temporalParse.llamaParse.config.anthropicApiKey | default "" | b64enc | quote }}
  {{- end }}
  {{- if and .Values.temporalParse.llamaParse.config.geminiApiKey (not .Values.temporalParse.llamaParse.config.existingGeminiApiKeySecret) }}
  GOOGLE_GEMINI_API_KEY: {{ .Values.temporalParse.llamaParse.config.geminiApiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.temporalParse.llamaParse.config.awsBedrock.enabled (not .Values.temporalParse.llamaParse.config.awsBedrock.existingSecret) }}
  AWS_BEDROCK_ENABLED: {{ "true" | b64enc | quote }}
  AWS_BEDROCK_REGION: {{ .Values.temporalParse.llamaParse.config.awsBedrock.region | b64enc | quote }}
  AWS_BEDROCK_ACCESS_KEY: {{ .Values.temporalParse.llamaParse.config.awsBedrock.accessKeyId | b64enc | quote }}
  AWS_BEDROCK_SECRET_KEY: {{ .Values.temporalParse.llamaParse.config.awsBedrock.secretAccessKey | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_3_5_VERSION_NAME: {{ .Values.temporalParse.llamaParse.config.awsBedrock.sonnet3_5ModelVersionName | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_3_7_VERSION_NAME: {{ .Values.temporalParse.llamaParse.config.awsBedrock.sonnet3_7ModelVersionName | b64enc | quote }}
  BEDROCK_ANTHROPIC_SONNET_4_0_VERSION_NAME: {{ .Values.temporalParse.llamaParse.config.awsBedrock.sonnet4_0ModelVersionName | b64enc | quote }}
  BEDROCK_ANTHROPIC_HAIKU_3_5_VERSION_NAME: {{ .Values.temporalParse.llamaParse.config.awsBedrock.haiku3_5_ModelVersionName | b64enc | quote }}
  {{- end }}
  {{- if and .Values.temporalParse.llamaParse.config.googleVertexAi.enabled (not .Values.temporalParse.llamaParse.config.googleVertexAi.existingSecret) }}
  GOOGLE_VERTEX_AI_ENABLED: {{ "true" | b64enc | quote }}
  GOOGLE_VERTEX_AI_PROJECT_ID: {{ .Values.temporalParse.llamaParse.config.googleVertexAi.projectId | b64enc | quote }}
  GOOGLE_VERTEX_AI_LOCATION: {{ .Values.temporalParse.llamaParse.config.googleVertexAi.location | b64enc | quote }}
  GOOGLE_VERTEX_AI_CREDENTIALS_JSON: {{ .Values.temporalParse.llamaParse.config.googleVertexAi.credentialsJson | b64enc | quote }}
  {{- end }}
  {{if .Values.temporalParse.llamaParse.config.writeDirectory }}
    LLAMAPARSE_WRITE_DIRECTORY: {{ .Values.temporalParse.llamaParse.config.writeDirectory | b64enc | quote }}
  {{- end}}
{{- end }}
{{- end -}}
