{{- if not .Values.global.config.existingLicenseKeySecret }}
{{- if empty .Values.global.config.licenseKey }}
{{- fail ".Value.global.config.licenseKey cannot be empty. Please provide a valid license key" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llamacloud.fullname" . }}-license-key
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
data:
  llamacloud-license-key: {{ .Values.global.config.licenseKey | b64enc | quote }}
{{- end }}
