apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: llamaparse-ocr

namespace: llamacloud

namePrefix: llamacloud-

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/component: llamacloud-llamaparse-ocr
    app.kubernetes.io/instance: llamacloud
    app.kubernetes.io/name: llamacloud

resources:
- ./base/service.yaml
- ./base/serviceaccount.yaml
- ./base/deployment.yaml
- ./base/pdb.yaml

secretGenerator:
- files:
  - license-key
  options:
    disableNameSuffixHash: true
  name: license-key
