apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.usage.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with .Values.usage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with .Values.usage.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.usage.autoscaling.enabled }}
  replicas: {{ .Values.usage.replicas }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "llamacloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.usage.name }}
  template:
    metadata:
      {{- with .Values.usage.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.usage.name }}
        {{- include "llamacloud.labels" . | nindent 8 }}
        {{- with .Values.usage.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "usage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.usage.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.usage.name | default "usage" }}
          securityContext:
            {{- toYaml .Values.usage.securityContext | nindent 12 }}
          image: "{{ .Values.usage.image.repository }}:{{ .Values.usage.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.usage.image.pullPolicy }}
          ports:
            - name: {{ .Values.usage.name }}-http
              containerPort: {{ .Values.usage.containerPort }}
              protocol: TCP
          command:
            - "uvicorn"
            - "app.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - {{ .Values.usage.containerPort | quote }}
            - "--workers"
            - "1"
          livenessProbe:
            {{- toYaml .Values.usage.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.usage.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.usage.resources | nindent 12 }}
          env:
          - name: LLAMACLOUD_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                {{- if .Values.global.config.existingLicenseKeySecret }}
                name: {{ .Values.global.config.existingLicenseKeySecret }}
                {{- else }}
                name: {{ include "llamacloud.fullname" . }}-license-key
                {{- end }}
                key: llamacloud-license-key
          {{- if .Values.mongodb.enabled }}
          - name: MONGODB_HOST
            value: {{ printf "%s-%s" .Release.Name (default "mongodb" .Values.mongodb.nameOverride) | quote }}
          - name: MONGODB_PORT
            value: {{ .Values.mongodb.service.port | default "27017" | quote }}
          - name: MONGODB_USER
            value: {{ .Values.mongodb.auth.rootUser | quote }}
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-%s" .Release.Name (default "mongodb" .Values.mongodb.nameOverride) | quote }}
                key: mongodb-root-password
          {{- end }}
          {{- if .Values.redis.enabled }}
          - name: REDIS_HOST
            value: {{ printf "%s-%s-master" (include "llamacloud.fullname" .) (default "redis" .Values.redis.nameOverride) | quote }}
          - name: REDIS_PORT
            value: {{ .Values.redis.master.service.ports.redis | default "6379" | quote }}
          {{- end }}
          {{- with .Values.usage.extraEnvVariables }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.usage.externalSecrets.enabled }}
          envFrom:
          {{- range .Values.usage.externalSecrets.secrets }}
          - secretRef:
              name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.usage.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.usage.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.usage.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.usage.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.usage.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
