apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.usage.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with .Values.usage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with .Values.usage.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.usage.autoscaling.enabled }}
  replicas: {{ .Values.usage.replicas }}
  {{- end }}
  progressDeadlineSeconds: {{ .Values.usage.progressDeadlineSeconds | default 1800 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "llamacloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.usage.name }}
  template:
    metadata:
      {{- with .Values.usage.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.usage.name }}
        {{- include "llamacloud.labels" . | nindent 8 }}
        {{- with .Values.usage.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "usage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.usage.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.usage.name | default "usage" }}
          securityContext:
            {{- toYaml .Values.usage.securityContext | nindent 12 }}
          image: "{{ .Values.usage.image.registry }}/{{ .Values.usage.image.repository }}:{{ .Values.usage.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.usage.image.pullPolicy }}
          ports:
            - name: {{ .Values.usage.name }}-http
              containerPort: {{ .Values.usage.containerPort }}
              protocol: TCP
          command:
            - "uvicorn"
            - "src.usage.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - {{ .Values.usage.containerPort | quote }}
            - "--workers"
            - "1"
            - "--timeout-keep-alive"
            - "300"
          livenessProbe:
            {{- toYaml .Values.usage.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.usage.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.usage.resources | nindent 12 }}
          env:
          - name: LLAMACLOUD_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                {{- if .Values.global.config.existingLicenseKeySecret }}
                name: {{ .Values.global.config.existingLicenseKeySecret }}
                {{- else }}
                name: {{ include "llamacloud.fullname" . }}-license-key
                {{- end }}
                key: llamacloud-license-key
          {{- include "common.mongodb.envVars" . | nindent 10 }}
          {{- include "common.postgresql.envVars" . | nindent 10 -}}
          {{- include "common.redis.envVars" . | nindent 10 }}
          {{- with .Values.usage.extraEnvVariables }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
          {{- if and (not .Values.mongodb.enabled) .Values.global.config.mongodb.external.enabled .Values.global.config.mongodb.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.mongodb.external.existingSecretName }}
          {{- end }}
          {{- if and (not .Values.postgresql.enabled) .Values.global.config.postgresql.external.enabled .Values.global.config.postgresql.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.postgresql.external.existingSecretName }}
          {{- end }}
          {{- if and (not .Values.redis.enabled) .Values.global.config.redis.external.enabled .Values.global.config.redis.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.redis.external.existingSecretName }}
          {{- end }}
          {{- range .Values.usage.externalSecrets.secrets }}
          - secretRef:
              name: {{ . }}
          {{- end }}
          {{- with .Values.usage.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.usage.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.usage.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.usage.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.usage.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
