apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.backend.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with .Values.backend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with .Values.backend.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicas }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "llamacloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.backend.name }}
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.backend.name }}
        {{- include "llamacloud.labels" . | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.backend.name | default "backend" }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: {{ .Values.backend.name }}-http
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
          command: ["python", "-m", "app.main"]
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.backend.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
          - name: LLAMACLOUD_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                {{- if .Values.global.config.existingLicenseKeySecret }}
                name: {{ .Values.global.config.existingLicenseKeySecret }}
                {{- else }}
                name: {{ include "llamacloud.fullname" . }}-license-key
                {{- end }}
                key: llamacloud-license-key
          {{- include "common.postgresql.envVars" . | nindent 10 -}}
          {{- include "common.mongodb.envVars" . | nindent 10 -}}
          {{- include "common.rabbitmq.envVars" . | nindent 10 -}}
          {{- include "common.redis.envVars" . | nindent 10 -}}
          {{- with .Values.backend.extraEnvVariables }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "llamacloud.fullname" . }}-{{ .Values.backend.name }}-config
          {{- if .Values.backend.config.oidc.existingSecretName }}
          - secretRef:
              name: {{ .Values.backend.config.oidc.existingSecretName }}
          {{- end }}
          {{- if .Values.backend.config.qdrant.existingSecret }}
          - secretRef:
              name: {{ .Values.backend.config.qdrant.existingSecret }}
          {{- end }}
          {{- if .Values.global.config.existingAwsSecretName }}
          - secretRef:
              name: {{ .Values.global.config.existingAwsSecretName }}
          {{- end }}
          {{- if .Values.backend.config.existingOpenAiApiKeySecretName }}
          - secretRef:
              name: {{ .Values.backend.config.existingOpenAiApiKeySecretName }}
          {{- end }}
          {{- if and .Values.backend.config.azureOpenAi.enabled .Values.backend.config.azureOpenAi.existingSecret }}
          - secretRef:
              name: {{ .Values.backend.config.azureOpenAi.existingSecret }}
          {{- end }}
          {{- if and (not .Values.postgresql.enabled) .Values.global.config.postgresql.external.enabled .Values.global.config.postgresql.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.postgresql.external.existingSecretName }}
          {{- end }}
          {{- if and (not .Values.mongodb.enabled) .Values.global.config.mongodb.external.enabled .Values.global.config.mongodb.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.mongodb.external.existingSecretName }}
          {{- end }}
          {{- if and (not .Values.rabbitmq.enabled) .Values.global.config.rabbitmq.external.enabled .Values.global.config.rabbitmq.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.rabbitmq.external.existingSecretName }}
          {{- end }}
          {{- if and (not .Values.redis.enabled) .Values.global.config.redis.external.enabled .Values.global.config.redis.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.redis.external.existingSecretName }}
          {{- end }}
          {{- if not .Values.backend.externalSecrets.enabled }}
          - secretRef:
              name: {{ include "llamacloud.fullname" . }}-{{ .Values.backend.name }}-secret
          {{- else }}
          {{- range .Values.backend.externalSecrets.secrets }}
          - secretRef:
              name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.backend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.backend.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
