{{- if not .Values.backend.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.backend.name }}-secret
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
data:
  {{- if and (eq .Values.global.cloudProvider "aws") .Values.global.config.awsAccessKeyId .Values.global.config.awsSecretAccessKey (not .Values.global.existingAwsSecretName) }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.config.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.config.awsSecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.backend.config.openAiApiKey (not .Values.backend.existingOpenAiApiKeySecretName) }}
  LC_OPENAI_API_KEY: {{ .Values.backend.config.openAiApiKey | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.backend.config.openAiApiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.backend.config.azureOpenAi.enabled (not .Values.backend.config.azureOpenAi.existingSecret) }}
  AZURE_OPENAI_API_KEY: {{ .Values.backend.config.azureOpenAi.key | b64enc | quote }}
  AZURE_OPENAI_BASE_URL: {{ .Values.backend.config.azureOpenAi.endpoint | b64enc | quote }}
  AZURE_OPENAI_GPT_4O_DEPLOYMENT_NAME: {{ .Values.backend.config.azureOpenAi.deploymentName | b64enc | quote }}
  AZURE_OPENAI_API_VERSION: {{ .Values.backend.config.azureOpenAi.apiVersion | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3proxy.enabled }}
  S3_ENDPOINT_URL: {{ printf "http://%s-%s:%d" (include "llamacloud.fullname" .) .Values.s3proxy.name (.Values.s3proxy.service.port | int) | b64enc | quote }}
  {{- end }}
  {{- if not .Values.backend.config.oidc.existingSecretName }}
  OIDC_DISCOVERY_URL: {{ .Values.backend.config.oidc.discoveryUrl | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.backend.config.oidc.clientId | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.backend.config.oidc.clientSecret | b64enc | quote }}
  SESSION_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.config.qdrant.enabled }}
  QDRANT_URL: {{ .Values.backend.config.qdrant.url | b64enc | quote }}
  QDRANT_API_KEY: {{ .Values.backend.config.qdrant.apiKey | b64enc | quote }}
  BYOC_HAS_MANAGED_QDRANT: {{ .Values.backend.config.qdrant.enabled | toString | lower | b64enc | quote }}
  {{- end }}
{{- end }}
