apiVersion: v1
kind: Service
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.backend.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with.Values.backend.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with.Values.backend.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.name }}-http
      protocol: TCP
  selector:
    {{- include "llamacloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.backend.name }}
