{{- $basicAuthEnabled := (((.Values.config).authentication).basicAuth).enabled }}
{{- $oidcEnabled := (((.Values.config).authentication).oidc).enabled }}
{{- $customerConfiguredEnabled := (((.Values.config).authentication).customerConfigured).enabled }}
{{- if or (or (and $basicAuthEnabled $oidcEnabled) (and $basicAuthEnabled $customerConfiguredEnabled)) (and $oidcEnabled $customerConfiguredEnabled) }}
{{- fail "Cannot enable more than one authentication method. Please choose basic authentication, OIDC authentication, or customer-configured authentication." -}}
{{- end }}
{{- if not (or $basicAuthEnabled (or $oidcEnabled $customerConfiguredEnabled)) }}
{{- fail "Must enable one authentication method. Please choose basic authentication, OIDC authentication, or customer-configured authentication." -}}
{{- end }}
{{- if $basicAuthEnabled }}
{{- if not (((.Values.config).authentication).basicAuth).secret }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "llamacloud.labels" (dict "root" $) | indent 4 }}
  annotations: {{ include "llamacloud.annotations" (dict "root" $) | indent 4 }}
data:
  BYOC_AUTH_MODE: {{ print "basic" | b64enc | quote }}
  BYOC_VALID_EMAIL_DOMAIN: {{ required ".Values.config.authentication.basicAuth.validEmailDomain is required when basic auth is enabled and no secret is provided" (((.Values.config).authentication).basicAuth).validEmailDomain | b64enc | quote }}
  BYOC_JWT_SECRET: {{ required ".Values.config.authentication.basicAuth.jwtSecret is required when basic auth is enabled and no secret is provided" (((.Values.config).authentication).basicAuth).jwtSecret | b64enc | quote }}
{{- end }}
{{- end }}
