apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsWorker.name }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with .Values.jobsWorker.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with .Values.jobsWorker.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.global.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ .Values.global.progressDeadlineSeconds | int }}
  {{- end }}
  {{- if not .Values.jobsWorker.autoscaling.enabled }}
  replicas: {{ .Values.jobsWorker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llamacloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsWorker.name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.jobsWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsWorker.name }}
        {{- include "llamacloud.labels" . | nindent 8 }}
        {{- with .Values.jobsWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jobsWorker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jobsWorker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.jobsWorker.name | default "jobs-worker" }}
          securityContext:
            {{- toYaml .Values.jobsWorker.securityContext | nindent 12 }}
          image: "{{ .Values.jobsWorker.image.registry }}/{{ .Values.jobsWorker.image.repository }}:{{ .Values.jobsWorker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jobsWorker.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.jobsWorker.containerPort }}
              protocol: TCP
          command: ["python", "-m", "src.jobs.consumer_main"]
          livenessProbe:
            {{- toYaml .Values.jobsWorker.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.jobsWorker.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.jobsWorker.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.jobsWorker.resources | nindent 12 }}
          env:
          - name: LLAMACLOUD_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                {{- if .Values.global.config.existingLicenseKeySecret }}
                name: {{ .Values.global.config.existingLicenseKeySecret }}
                {{- else }}
                name: {{ include "llamacloud.fullname" . }}-license-key
                {{- end }}
                key: llamacloud-license-key
          {{- include "common.postgresql.envVars" . | nindent 10 -}}
          {{- include "common.mongodb.envVars" . | nindent 10 -}}
          {{- include "common.rabbitmq.envVars" . | nindent 10 -}}
          {{- include "common.redis.envVars" . | nindent 10 -}}
          {{- with .Values.jobsWorker.extraEnvVariables }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsWorker.name }}-config
          {{- if .Values.global.config.existingAwsSecretName }}
          - secretRef:
              name: {{ .Values.global.config.existingAwsSecretName }}
          {{- end }}
          {{- if .Values.backend.config.existingOpenAiApiKeySecretName }}
          - secretRef:
              name: {{ .Values.backend.config.existingOpenAiApiKeySecretName }}
          {{- end }}
          {{- if and .Values.backend.config.azureOpenAi.enabled .Values.backend.config.azureOpenAi.existingSecret }}
          - secretRef:
              name: {{ .Values.backend.config.azureOpenAi.existingSecret }}
          {{- end }}
          {{- if and (not .Values.postgresql.enabled) .Values.global.config.postgresql.external.enabled .Values.global.config.postgresql.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.postgresql.external.existingSecretName }}
          {{- end }}
          {{- if and (not .Values.mongodb.enabled) .Values.global.config.mongodb.external.enabled .Values.global.config.mongodb.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.mongodb.external.existingSecretName }}
          {{- end }}
          {{- if and (not .Values.rabbitmq.enabled) .Values.global.config.rabbitmq.external.enabled .Values.global.config.rabbitmq.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.rabbitmq.external.existingSecretName }}
          {{- end }}
          {{- if and (not .Values.redis.enabled) .Values.global.config.redis.external.enabled .Values.global.config.redis.external.existingSecretName }}
          - secretRef:
              name: {{ .Values.global.config.redis.external.existingSecretName }}
          {{- end }}
          {{- if not .Values.jobsWorker.externalSecrets.enabled }}
          - secretRef:
              name: {{ include "llamacloud.fullname" . }}-{{ .Values.jobsWorker.name }}-secret
          {{- else }}
          {{- range .Values.jobsWorker.externalSecrets.secrets }}
          - secretRef:
              name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.jobsWorker.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.jobsWorker.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobsWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobsWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobsWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
