{{- if .Values.jobsWorker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jobsWorker.serviceAccountName" . }}
  labels:
    {{- include "llamacloud.labels" . | nindent 4 }}
    {{- with .Values.jobsWorker.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "llamacloud.annotations" . | nindent 4 }}
    {{- with .Values.jobsWorker.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.jobsWorker.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}
