name: Extract Alembic History

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  extract-history:
    name: "Extract Alembic History"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'
          check-latest: true

      - name: Extract Helm Chart Version
        id: extract-version
        run: |
          CHART_VERSION=$(grep '^version:' charts/llamacloud/Chart.yaml | awk '{print $2}')
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Run Extract Alembic History Script
        run: |
          echo "Testing Extract Alembic History Script for chart version $CHART_VERSION"
          chmod +x scripts/extract_alembic_history.sh
          ./scripts/extract_alembic_history.sh $CHART_VERSION
