name: Lint, Test, Install Charts

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint-test:
    name: "Lint and Test Helm Charts"
    runs-on:
      labels: helm-charts-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Lint
        id: lint-charts
        run: |
          ct lint \
            --target-branch ${{ github.event.repository.default_branch }} \
            --validate-maintainers=false \
            --check-version-increment=false

      - name: Setup helm unittest
        id: setup-helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Run Unit Test
        id: unit-test-charts
        run: |
          helm unittest ./charts/llamacloud

  install-test:
    name: "Install Helm Charts"

    needs: [lint-test]

    runs-on:
      labels: helm-charts-runner

    strategy:
      matrix:
        k8s-version:
          # Limit testing because tests can take a while to run
          # Ref: https://hub.docker.com/r/kindest/node/tags
          - v1.30.10
          - v1.32.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Test
        id: test-charts
        env:
          LLAMACLOUD_LICENSE_KEY: ${{ secrets.LLAMACLOUD_LICENSE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OIDC_DISCOVERY_URL: ${{ secrets.OIDC_DISCOVERY_URL }}
          OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
          OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
        run: |
          charts/llamacloud/ci/test-helm-install.sh
